### PR TITLE
Use late evaluation of $term variable for bindsym $mod+Return

### PR DESCRIPTION
**Pull request by mcepl**
So that an user can set different terminal application (or use different options for alacritty).

### CODE REVIEW

**Comment by denisok** [comment]
oh, cool - how it works ?

**Comment by mcepl** [comment]
> oh, cool - how it works ?

Lovely with
```
set $term alacritty --config-file ~/.config/alacritty/alacritty.yml
```
in `~/.config/sway/config.d/10-variables.conf` I use my personal configuration for alacritty.

**Comment by denisok** [comment]
cool, could you please point me to the double `$$` definition ?

**Comment by mcepl** [comment]
> cool, could you please point me to the double `$$` definition ?

sway(5):
 ```
set $<name> <value>
           Sets variable $name to value. You can use the new variable in the arguments of future commands.
When the variable is used, it can be escaped with an additional $ (ie $$name) to have the replacement happen
at run time instead of when reading the config. However, it does not always make sense for the variable to be
replaced at run time since some arguments do need to be known at config time.
```

**Comment by denisok** [comment]
Thanks for educating me! :)

**Pull request merged**
