### PR TITLE
number of packages to update indicator to waybar

### LINKED ISSUE #40: An other suggestion: Update indicator (waybar)
Hi!
This may be just a personal wish, not sure if anyone else wants this: May I suggest to include an update widget to waybar . I have something like this:

```
  "custom/zypper": {
        "format": "{} ",
        "interval": 3600,
        "exec": "zypper lu | grep 'v |' | wc -l",
        "exec-if": "exit 0",
        "on-click": "exec alacritty -e sudo  zypper update ; pkill -SIGRTMIN+8 waybar",
        "signal": 8
    }
```
I must confess that I copied -and slighty adapted- the code from waybar's wiki...I am not 100% about this SIGTMIN+signal function...but heyho, it seems to do what it should do.

Cheers

### PR DESCRIPTION
**Pull request by denisok**
fixes #40

### CODE REVIEW

**Comment by denisok** [comment]
`pkill -SIGRTMIN+8 waybar` is actually what reloads waybar after the update.

**Comment by taschenlampe** [comment]
> `pkill -SIGRTMIN+8 waybar` is actually what reloads waybar after the update.

Unfortunately, I cannot confirm this :-S
 My observations is a follows:
The script is running and refreshes itself (interval). As soon as one clicks the icon the script -> loads 1.command: zypper lu + 2. start zypper in alacritty + 3 kills alacritty after zypper exits
Result: the number that 1.command zypper lu gave after initial clicking stays and does get not refresh immediately -only after interval. 

I also tested with
```

    "custom/test": {
        "format": "{} ",
        "interval": 30,
        "exec": "cat /home/kokko/count.txt | wc -l; echo 'test'",
        "exec-if": "exit 0",
        "on-click": "exec alacritty -e sudo  zypper dup ; pkill -SIGRTMIN+8 waybar",
        "signal": 8
    },
```
I will install a virtualbox, that will run the openSUSEway configuration solely, so I have a real reference, to reduce possible interferences. 

Cheers

**Comment by denisok** [comment]
according to https://github.com/Alexays/Waybar/wiki/Module:-Custom `signal` is exactly for that.
I checked and it works, but I slightly modified the config. Will update it.

**Comment by taschenlampe** [comment]
Ok...I tested your config: works for me.

**Pull request merged**
